name = "landing"
compatibility_date = "2025-05-29"

# Configuración para Pages Functions
pages_build_output_dir = "dist"

# Variables de entorno (opcional)
[env.production.vars]
API_BASE_URL = "https://botai.smartdataautomation.com"

# Configuración de assets (ya no es necesaria con pages_build_output_dir)
# [assets]
# directory = "./dist"