name = "landing"
compatibility_date = "2025-05-29"

# Como estamos en Landing/, dist está en la misma carpeta
pages_build_output_dir = "dist"  

[env.production.vars]
API_BASE_URL = "https://botai.smartdataautomation.com"